github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

docker_credentials:
- registry: ghcr.io
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  password: ${{ secrets.JAVA_GITHUB_TOKEN }}

actions:
- source: adoptium-dependency
  target: ghcr.io/paketo-buildpacks/actions/adoptium-dependency
- source: amazon-corretto-dependency
  target: ghcr.io/paketo-buildpacks/actions/amazon-corretto-dependency
- source: alibaba-dragonwell-dependency
  target: ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency
- source: appdynamics-dependency
  target: ghcr.io/paketo-buildpacks/actions/appdynamics-dependency
- source: aqua-security-dependency
  target: ghcr.io/paketo-buildpacks/actions/aqua-security-dependency
- source: azul-zulu-dependency
  target: ghcr.io/paketo-buildpacks/actions/azul-zulu-dependency
- source: bellsoft-liberica-dependency
  target: ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency
- source: ca-apm-dependency
  target: ghcr.io/paketo-buildpacks/actions/ca-apm-dependency
- source: cf-java-index-dependency
  target: ghcr.io/paketo-buildpacks/actions/cf-java-index-dependency
- source: clojure-tools-dependency
  target: ghcr.io/paketo-buildpacks/actions/clojure-tools-dependency
- source: foojay-dependency
  target: ghcr.io/paketo-buildpacks/actions/foojay-dependency
- source: gcs-dependency
  target: ghcr.io/paketo-buildpacks/actions/gcs-dependency
- source: github-release-dependency
  target: ghcr.io/paketo-buildpacks/actions/github-release-dependency
- source: google-stackdriver-profiler-dependency
  target: ghcr.io/paketo-buildpacks/actions/google-stackdriver-profiler-dependency
- source: graalvm-dependency
  target: ghcr.io/paketo-buildpacks/actions/graalvm-dependency
- source: gradle-dependency
  target: ghcr.io/paketo-buildpacks/actions/gradle-dependency
- source: ibm-semeru-dependency
  target: ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency
- source: jprofiler-dependency
  target: ghcr.io/paketo-buildpacks/actions/jprofiler-dependency
- source: jrebel-dependency
  target: ghcr.io/paketo-buildpacks/actions/jrebel-dependency
- source: leiningen-dependency
  target: ghcr.io/paketo-buildpacks/actions/leiningen-dependency
- source: maven-dependency
  target: ghcr.io/paketo-buildpacks/actions/maven-dependency
- source: new-relic-dependency
  target: ghcr.io/paketo-buildpacks/actions/new-relic-dependency
- source: npm-dependency
  target: ghcr.io/paketo-buildpacks/actions/npm-dependency
- source: overops-dependency
  target: ghcr.io/paketo-buildpacks/actions/overops-dependency
- source: paketo-deps-dependency
  target: ghcr.io/paketo-buildpacks/actions/paketo-deps-dependency
- source: riverbed-dependency
  target: ghcr.io/paketo-buildpacks/actions/riverbed-dependency
- source: rustup-init-dependency
  target: ghcr.io/paketo-buildpacks/actions/rustup-init-dependency
- source: skywalking-dependency
  target: ghcr.io/paketo-buildpacks/actions/skywalking-dependency
- source: spring-generations
  target: ghcr.io/paketo-buildpacks/actions/spring-generations
- source: tomcat-dependency
  target: ghcr.io/paketo-buildpacks/actions/tomcat-dependency
- source: yourkit-dependency
  target: ghcr.io/paketo-buildpacks/actions/yourkit-dependency
