---
name: github.com/paketo-buildpacks/azure-application-insights
package:
  repository: gcr.io/paketo-buildpacks/azure-application-insights
  username: _json_key
  password: ((artifact-gcs-json-key))

dependencies:
  - name: azure-application-insights-java
    type: github-release
    icon: github-circle
    source:
      owner:        Microsoft
      repository:   ApplicationInsights-Java
      access_token: ((github-access-token))
    params:
      globs:
        - applicationinsights-agent-*.jar
  - name: azure-application-insights-nodejs
    type: npm-resource
    icon: npm
    source:
      package:     applicationinsights
      pre_release: false
