---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: pipeline-builder

outputs:
  - name: adopt-openjdk-resource
  - name: amazon-corretto-resource
  - name: azul-zulu-resource
  #  - name: artifactory-builder
  - name: bellsoft-liberica-resource
  - name: gradle-resource
  #  - name: http-builder
  #  - name: jprofiler-builder
  - name: maven-resource
  - name: npm-resource
  - name: repository-resource
#  - name: sky-walking-builder
#  - name: tomcat-builder
#  - name: wildfly-builder
#  - name: your-kit-builder

caches:
  - path: go-cache

run:
  path: pipeline-builder/scripts/build.sh
