---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: pipeline-builder

outputs:
  - name: adopt-openjdk-resource
  - name: amazon-corretto-resource
  - name: appdynamics-resource
  - name: azul-zulu-resource
  - name: bellsoft-liberica-resource
  - name: gradle-resource
  - name: jrebel-resource
  - name: jprofiler-resource
  - name: maven-resource
  - name: new-relic-resource
  - name: npm-resource
  - name: registry-image-version-resource
  - name: stackdriver-profiler-resource
  - name: skywalking-resource
  - name: tomcat-resource
  - name: yourkit-resource

caches:
  - path: go-cache

run:
  path: pipeline-builder/scripts/build.sh
